/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Sockets;

import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JOptionPane;

//UDP -> Troca de dados sem necessidade de confirmação
//TCP -> Troca confiável de dados
//Socket -> Definir a porta que fica aguardando os dados e o tipo de conexão com o cliente

public class ServidorTCP {

    public static void main(String[] args) {
        try{
            ServerSocket servidor = new ServerSocket(8888); //de 0 a 1024 não usamos
            String dados = "Mensagem: " + JOptionPane.showInputDialog("Digite: ");
            while(true){
                Socket cliente = servidor.accept();
                ObjectOutputStream saida = new ObjectOutputStream(cliente.getOutputStream());
                saida.flush();
                saida.writeUTF(dados);
                saida.close();
                cliente.close();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }
}
