/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dektop;

import static java.lang.System.out;
import java.net.InetAddress;
import java.net.MulticastSocket;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import servidor.fileManager;
import java.net.DatagramPacket;
import javax.swing.JOptionPane;


/**
 *
 * @author walla
 */
public class Desktop2 extends javax.swing.JFrame {

        Thread thread1;
        Thread thread2;
    
    /**
     * Creates new form Desktop2
     */
    public Desktop2() {
        initComponents();
        
        new Thread(()->{
            while(true){
                String sRet = "";
                    try{
                        MulticastSocket socketMulticast = new MulticastSocket(4444);
                        InetAddress grupo = InetAddress.getByName("239.0.0.1");
                        socketMulticast.joinGroup(grupo);
                        byte[] b = new byte[256];
                        DatagramPacket datagrama = new DatagramPacket(b, b.length);
                        socketMulticast.receive(datagrama);
                        sRet = new String(datagrama.getData()).trim();
                        //JOptionPane.showMessageDialog(null,"Mensagem: " + sRet);

                        if(null != sRet)switch (sRet) {
                            case "1":
                                jLabel2.setIcon(new ImageIcon("C:\\Users\\walla\\OneDrive\\Documentos\\NetBeansProjects\\Chat_com_threads\\src\\main\\java\\Dektop\\images\\coca-cola.jpg"));
                                break;
                            case "2":
                                jLabel2.setIcon(new ImageIcon("C:\\Users\\walla\\OneDrive\\Documentos\\NetBeansProjects\\Chat_com_threads\\src\\main\\java\\Dektop\\images\\fanta.jpg"));
                                break;
                            case "3":        
                                jLabel2.setIcon(new ImageIcon("C:\\Users\\walla\\OneDrive\\Documentos\\NetBeansProjects\\Chat_com_threads\\src\\main\\java\\Dektop\\images\\pepsi.jpg"));
                                break;
                            default:
                                break;
                        }
                    }
                    catch(Exception e){
                        e.printStackTrace();
                    }
                }
        }).start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        mensagem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jEditorPane1.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(jEditorPane1);

        jLabel1.setText("Mensagem");

        mensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensagemActionPerformed(evt);
            }
        });

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(mensagem.getText() != null){
            Registry reg = null;  //do Desktop
            Registry reg2 = null; //do Web
            try {
                reg = LocateRegistry.getRegistry("localhost",4444);
                reg2 = LocateRegistry.getRegistry("localhost",5555);
            } catch (RemoteException ex) {
                Logger.getLogger(Desktop2.class.getName()).log(Level.SEVERE, null, ex);
            }
            fileManager obj = null;
            fileManager obj2 = null;
            try {
                obj = (fileManager) reg.lookup("manager");
                obj2 = (fileManager) reg2.lookup("manager");
                
                Threads tdesktop = new Threads();
                Threads tweb = new Threads();
                
                tdesktop.setParameters(obj, "<br>" + Util.nick + "diz: " + mensagem.getText() + "<br>");
                tweb.setParameters(obj2, "<br>" + Util.nick + "diz: " + mensagem.getText() + "<br>");
                
                thread1 = new Thread(tdesktop);
                thread1.start();
                
                thread2 = new Thread(tweb);
                thread2.start();
                
               
                
                jEditorPane1.setText(obj.retrieve());
            } catch (RemoteException ex) {
                Logger.getLogger(Desktop2.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(Desktop2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mensagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desktop2().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mensagem;
    // End of variables declaration//GEN-END:variables
}
